/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      colors: {
        primary: '#3856c4',
        'primary-container': '#6d89fa',
        'primary-dim': '#2949b7',
        'on-primary': '#faf8ff',
        'on-primary-container': '#000a36',
        secondary: '#526074',
        'secondary-container': '#d5e3fc',
        'on-secondary': '#f8f8ff',
        'on-secondary-container': '#455367',
        tertiary: '#6f557d',
        'tertiary-container': '#efcffe',
        'on-tertiary': '#fff6fd',
        error: '#a8364b',
        'error-container': '#f97386',
        'on-error': '#fff7f7',
        background: '#f7f9fb',
        'on-background': '#2c3437',
        surface: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d4dbdf',
        'surface-container': '#eaeff2',
        'surface-container-high': '#e3e9ed',
        'surface-container-highest': '#dce4e8',
        'surface-container-low': '#f0f4f7',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#2c3437',
        'on-surface-variant': '#596064',
        outline: '#747c80',
        'outline-variant': '#acb3b7',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
        'inverse-primary': '#6d89fa',
        'surface-tint': '#3856c4',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.375rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        full: '9999px',
      },
      boxShadow: {
        editorial: '0 20px 40px rgba(44, 52, 55, 0.06)',
        soft: '0 4px 16px rgba(44, 52, 55, 0.04)',
        elevated: '0 8px 32px rgba(44, 52, 55, 0.12)',
      },
      backdropBlur: {
        glass: '16px',
      },
      spacing: {
        18: '4.5rem',
      },
    },
  },
  plugins: [],
}
