/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      colors: {
        primary:                    'rgb(var(--c-primary) / <alpha-value>)',
        'primary-container':        'rgb(var(--c-primary-container) / <alpha-value>)',
        'primary-dim':              'rgb(var(--c-primary-dim) / <alpha-value>)',
        'on-primary':               'rgb(var(--c-on-primary) / <alpha-value>)',
        'on-primary-container':     'rgb(var(--c-on-primary-container) / <alpha-value>)',
        secondary:                  'rgb(var(--c-secondary) / <alpha-value>)',
        'secondary-container':      'rgb(var(--c-secondary-container) / <alpha-value>)',
        'on-secondary':             'rgb(var(--c-on-secondary) / <alpha-value>)',
        'on-secondary-container':   'rgb(var(--c-on-secondary-container) / <alpha-value>)',
        tertiary:                   'rgb(var(--c-tertiary) / <alpha-value>)',
        'tertiary-container':       'rgb(var(--c-tertiary-container) / <alpha-value>)',
        'on-tertiary':              'rgb(var(--c-on-tertiary) / <alpha-value>)',
        error:                      'rgb(var(--c-error) / <alpha-value>)',
        'error-container':          'rgb(var(--c-error-container) / <alpha-value>)',
        'on-error':                 'rgb(var(--c-on-error) / <alpha-value>)',
        background:                 'rgb(var(--c-background) / <alpha-value>)',
        'on-background':            'rgb(var(--c-on-background) / <alpha-value>)',
        surface:                    'rgb(var(--c-surface) / <alpha-value>)',
        'surface-bright':           'rgb(var(--c-surface-bright) / <alpha-value>)',
        'surface-dim':              'rgb(var(--c-surface-dim) / <alpha-value>)',
        'surface-container':        'rgb(var(--c-surface-container) / <alpha-value>)',
        'surface-container-high':   'rgb(var(--c-surface-container-high) / <alpha-value>)',
        'surface-container-highest':'rgb(var(--c-surface-container-highest) / <alpha-value>)',
        'surface-container-low':    'rgb(var(--c-surface-container-low) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
        'on-surface':               'rgb(var(--c-on-surface) / <alpha-value>)',
        'on-surface-variant':       'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        outline:                    'rgb(var(--c-outline) / <alpha-value>)',
        'outline-variant':          'rgb(var(--c-outline-variant) / <alpha-value>)',
        'inverse-surface':          'rgb(var(--c-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':       'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
        'inverse-primary':          'rgb(var(--c-inverse-primary) / <alpha-value>)',
        'surface-tint':             'rgb(var(--c-surface-tint) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.375rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        full: '9999px',
      },
      boxShadow: {
        editorial: '0 20px 40px rgba(44, 52, 55, 0.06)',
        soft: '0 4px 16px rgba(44, 52, 55, 0.04)',
        elevated: '0 8px 32px rgba(44, 52, 55, 0.12)',
      },
      backdropBlur: {
        glass: '16px',
      },
      spacing: {
        18: '4.5rem',
      },
    },
  },
  plugins: [],
}
